var notSure = 4;
console.log(notSure);
notSure = "Bal bichi Typescript";
console.log(notSure);
notSure = false;
console.log(notSure);
var myArr = [1, true, "dhur bal"];
console.log(myArr);
myArr[0] = "Bhalo lagche na";
console.log(myArr);
