/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EclipseGradleJava;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
		System.out.println("Welcome to Zensar! Like for the 100th time!");
	}
}
